name: Test Build Desktop App

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - windows
          - macos
          - linux

permissions:
  contents: read

jobs:
  test-build-windows:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'windows' }}
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build for Windows
        run: npm run build:win
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-windows
          path: dist/
          retention-days: 7

  test-build-macos:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'macos' }}
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build for macOS
        run: npm run build:mac
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-macos
          path: dist/
          retention-days: 7

  test-build-linux:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'linux' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build for Linux
        run: npm run build:linux
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-linux
          path: dist/
          retention-days: 7
